### ISSUE TITLE
Cannot load openstudio.rb from install dir

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#407]
Issue overview
--------------
Cannot load openstudio.rb from install dir

## Current Behavior
`ruby -I /c/openstudioapplication-1.2.1/Ruby/ -e "require 'openstudio'"`

or:

`ruby -I /c/openstudioapplication-1.2.1/Ruby/ -e "require 'openstudio_modeleditor'"`

results in:

```
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/dll_directory.rb:83:in `add_dll_directory_winapi': AddDllDirectory failed for C:/openstudioapplication-1.2.1/lib (RubyInstaller::Runtime::DllDirectory::WinApiError)
        from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/dll_directory.rb:50:in `initialize'
        from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/singleton.rb:12:in `new'
        from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/singleton.rb:12:in `add_dll_directory'
        from C:/openstudioapplication-1.2.1/Ruby/openstudio.rb:46:in `<top (required)>'
        from C:/openstudioapplication-1.2.1/Ruby/openstudio_modeleditor.rb:80:in `require_relative'
        from C:/openstudioapplication-1.2.1/Ruby/openstudio_modeleditor.rb:80:in `<top (required)>'
        from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
```

## Expected Behavior
It should succeed

**Comment by macumber** [comment]
As a workaround, users wanting to run Ruby scripts loading OpenStudio Ruby bindings can install the OS SDK independently and load the Ruby bindings from there.
